#' @keywords internal
"_PACKAGE"


.globals <- new.env(parent = emptyenv())

# ' @exportS3Method reticulate::py_to_r
py_to_r.markitdown.DocumentConverterResult <- function(x) {
  c(title = x$title, text = x$text_content)
}


.onLoad <- function(libname, pkgname) {
  Sys.setenv(RETICULATE_PYTHON = "managed")
  reticulate::py_require(c("markitdown" = "git+https://github.com/microsoft/markitdown.git@main#subdirectory=packages/markitdown"))

  reticulate:::py_register_load_hook("markitdown", function() {

    registerS3method(
      "py_to_r",
      nameOfClass(reticulate::import("markitdown")$DocumentConverterResult),
      py_to_r.markitdown.DocumentConverterResult,
      environment(reticulate::py_to_r)
    )

    # `_CustomMarkdownify` <- reticulate::import("markitdown._markitdown")$`_CustomMarkdownify`
    # og_convert_a <- `_CustomMarkdownify`$convert_a
    # `_CustomMarkdownify`$convert_a <- function(self, el, text, convert_as_inline) {
    #   # patch to prevent generating links in the markdown if
    #   # - if the link is in a pre-formatted code block
    #   # - if the link is to rdrr.io/r (autogenerated by pkgdown)
    #   tryCatch({
    #     if (el$get("href", "") |> startsWith("https://rdrr.io/r")) {
    #       return(text)
    #     }
    #
    #     if (!is.null(el$find_parent("pre"))) {
    #       return(text)
    #     }
    #   }, error = warning)
    #
    #   og_convert_a(self, el, text, convert_as_inline)
    # }
  })
}
